data:
  - http://aanghigia.blogspot.co.id
  - http://aasnuraisiyah.blogspot.com
  - http://agiluin.blogspot.co.id
  - http://ahnaniyah.blogspot.co.id
  - http://aisyarifi.wordpress.com
  - http://alfianosekai.blogspot.co.id
  - http://alfierani.blogspot.co.id
  - http://aliefkiekie.blogspot.co.id
  - http://andhikamppp.com
  - http://andiniyulina.blogspot.co.id
  - http://andypracreativity.wordpress.com
  - http://anggakim-story.blogspot.co.id
  - http://aprilecuma.blogspot.com
  - http://atikahbakir.wordpress.com
  - http://aufnote.wordpress.com/
  - http://auli3ainun.blogspot.co.id
  - http://banggober.blogspot.co.id
  - http://bariku4.blogspot.co.id
  - http://belajarkoding.net/
  - http://bintangpamungkas.blogspot.com
  - http://blog.martinfenner.org/
  - http://blograsacerita.wordpress.com
  - http://bolehdikepoin.blogspot.co.id
  - http://bulantheirongirl.blogspot.com
  - http://buner77.wordpress.com
  - http://cahayasabit91.blogspot.co.id
  - http://caklutfi.blogspot.co.id
  - http://caritakita.wordpress.com
  - http://catatanbukudiah.wordpress.com
  - http://cerpenmu.com
  - http://chairulnisaa.wordpress.com
  - http://chairulsinaga.blogspot.com
  - http://coretanbasayev.blogspot.co.id
  - http://coretanbasayev.blogspot.com
  - http://coretanrifqi.blogspot.com
  - http://css-tricks.com/
  - http://cutdekayi.com
  - http://dear-diah.blogspot.com
  - http://dewieajaa.blogspot.my
  - http://dewiultralight08.wordpress.com/
  - http://dhicovelian.wordpress.com
  - http://dianravi.com
  - http://didotanindita.blogspot.com
  - http://dlaraz.blogspot.co.id
  - http://dloverheruwidayanto.blogspot.co.id
  - http://dongeng-malam.blogspot.co.id
  - http://donnaimelda.com
  - http://dunia-digital.com/
  - http://duniabiza.com
  - http://duniaraisha.wordpress.com
  - http://dweedy.blogspot.com
  - http://edisipertama.wordpress.com
  - http://ergiwhey.wordpress.com/
  - http://erinajulia.wordpress.com
  - http://eternallord.blogspot.co.id/
  - http://evrinasp.wordpress.com
  - http://fandhyachmadromadhon.blogspot.com
  - http://farhanakal.blogspot.com
  - http://frizkum.blogspot.com
  - http://girlwithwritingproblems.wordpress.com
  - http://graffitimimpi.blogspot.co.id
  - http://gudesmaa.blogspot.co.id
  - http://halamancermin.blogspot.com
  - http://hamledcreation.blogspot.co.id/
  - http://hamtiar.com/
  - http://hatidanpikiranjernih.blogspot.com
  - http://hedirizky.blogspot.co.id
  - http://himapsiunmul.blogspot.com
  - http://hudasyahdan.blogspot.com
  - http://id.kb.kangamir.my.id
  - http://id.techinasia.com
  - http://idntimes.com
  - http://ilarizky.blogspot.com
  - http://Ilmitamami.blogspot.co.id
  - http://indahnaynes.blogspot.co.id
  - http://intanrainy.wordpress.com/
  - http://isykarima.com
  - http://jakartamajubersama.com/rilis-media
  - http://jalantikus.com/
  - http://japanesestation.com/latest-from-japan/
  - http://jemarihati23.blogspot.co.id
  - http://jurnalotaku.com/all
  - http://justformylucky.blogspot.com/
  - http://kafekopi.blogspot.com
  - http://kangferyfadli.wordpress.com
  - http://kangrudi.com
  - http://kaorinusantara.or.id
  - http://kapalkertasbangjee.blogspot.co.id
  - http://kaskus.co.id
  - http://keluargahamsa.com/
  - http://kisahduduk.blogspot.co.id
  - http://konsultasisyariah.com/
  - http://lailatulisbach.blogspot.co.id
  - http://laylisyarifah.blogspot.co.id
  - http://lendyagasshi.com
  - http://lisasurya.blogspot.co.id
  - http://liswanti627.blogspot.com
  - http://luckty.wordpress.com
  - http://mabrurohqosim.blogspot.co.id
  - http://madamemandana.blogspot.com.au
  - http://mansurjihad.com
  - http://martikasandra.blogspot.co.id
  - http://mbakdhe.blogspot.co.id
  - http://medium.com/
  - http://medium.com/@mxwan
  - http://medium.com/alisoftware
  - http://menarahati.wordpress.com
  - http://miamiamoy.blogspot.com
  - http://miftaresti.blogspot.com
  - http://mimithpunyacerita.blogspot.com
  - http://mojok.co
  - http://mswijaya.blogspot.co.id
  - http://muflihramadhan.com
  - http://muhammadzaini.com
  - http://mulazamah.com
  - http://mumaken.blogspot.com
  - http://mursyidsyaifulhaq27.blogspot.co.id
  - http://muslimdaily.net
  - http://nanaumza.blogspot.co.id
  - http://ndansono.com/
  - http://netriolala.blogspot.com
  - http://niisya.wordpress.com
  - http://nonirosliyani.com
  - http://noviaanggrainiej.blogspot.co.id
  - http://nsetyo.com
  - http://nulsquotary.blogspot.co.id
  - http://opikfreetime.blogspot.co.id
  - http://otacouncil.com/
  - http://pebriika.blogspot.co.id
  - http://penafauzi-yah.blogspot.co.id
  - http://perjalananseru.wordpress.com
  - http://pisangbenjol.wordpress.com
  - http://psychoanalyticmuse.blogspot.co.id/
  - http://rahayuhestiningsih.blogspot.co.id
  - http://raihanamahmud.blogspot.my
  - http://reallysweetlife.blogspot.co.id
  - http://rezhajulio.id
  - http://rindhuhati.blogspot.co.id/
  - http://rizkaalyna.blogspot.com
  - http://robbybie.com
  - http://ruangrumpi.wordpress.com
  - http://rumahjemarialiana.blogspot.co.id
  - http://sabitmoon1.blogspot.com
  - http://safinarhyy21.blogspot.co.id
  - http://sandibrand.id/
  - http://sehatisehatselalu.blogspot.co.id
  - http://seindahsunnah.com/
  - http://simeuthejo.blogspot.co.id
  - http://sinaudev.org
  - http://siochoy.wordpress.com
  - http://situsali.com
  - http://societyforhumanisticpsychology.blogspot.co.id/
  - http://soviatriana.blogspot.co.id
  - http://storyofemakcodetz.blogspot.com
  - http://storyofrene.blogspot.co.id
  - http://surgabukuku.blogspot.com
  - http://syamthofa.wordpress.com/
  - http://syarifatulindra.blogspot.co.id
  - http://tamvandanberani.blogspot.com
  - http://titikeke.com
  - http://trisnafadliyah.com
  - http://tutorialzine.com/articles
  - http://ulanaprilisdy.blogspot.co.id
  - http://unyumenyunyu.blogspot.com
  - http://veekaybee.github.io/
  - http://vmatmanegara.blogspot.com
  - http://www.alidabdul.com/
  - http://www.andriyani.web.id
  - http://www.aniskhoir.com
  - http://www.annisaprasetyo.com
  - http://www.cemaru.com
  - http://www.cewealpukat.me
  - http://www.codepolitan.com/articles
  - http://www.daemonology.net/hn-daily/
  - http://www.dokterforamen.com
  - http://www.enigmablogger.com/
  - http://www.fahmirabbani.com
  - http://www.gendhiss.com
  - http://www.hipwee.com/terbaru/
  - http://www.idatahmidah.com/
  - http://www.ijeverson.com
  - http://www.ilhamkusumaning.com
  - http://www.it-jurnal.com/
  - http://www.jagocoding.com/tutorial
  - http://www.jungjawa.com/
  - http://www.jurnalweb.com
  - http://www.kartunet.com
  - http://www.lapakmedan.com
  - http://www.maxmanroe.com
  - http://www.mondayflashfiction.com/
  - http://www.nfirmansyah.com
  - http://www.nodiwa.com
  - http://www.novawijaya.com
  - http://www.nurulfitri.com/
  - http://www.nyorett.com
  - http://www.okymaulana.com/
  - http://www.petanikode.com/
  - http://www.positivelife.ml
  - http://www.psychologytoday.com/
  - http://www.ridoarbain.com/
  - http://www.shitlicious.com/
  - http://www.smashingmagazine.com/
  - http://www.solostream.com/blog/
  - http://www.syaiha.com
  - http://www.syiahindonesia.com
  - http://www.titisayuningsih.com
  - http://www.tukangjalanjajan.com
  - http://www.unidzalika.com
  - http://www.wignyaharsono.com
  - http://www.wordholic.com
  - http://yukkimura.blogspot.co.id/
  - http://zeelazeal.blogspot.co.id
  - http://zharnd.net
  - https://thehackernews.com/
  - https://hackernoon.com/