data:
  - http://kaorinusantara.or.id
  - http://www.mulazamah.com/?m=1
  - http://blog.meubelmart.com/
  - http://www.alidabdul.com/
  - http://www.idatahmidah.com/
  - http://ndansono.com/
  - http://rindhuhati.blogspot.co.id/
  - http://www.ridoarbain.com/?m=1
  - http://www.jungjawa.com/?m=1
  - http://www.jurnalweb.com
  - https://www.maxmanroe.com
  - https://id.kb.kangamir.my.id
  - http://kafekopi.blogspot.com
  - http://mansurjihad.com
  - http://www.nfirmansyah.com
  - http://www.nurulfitri.com/
  - http://www.okymaulana.com/
  - http://sandibrand.id/
  - http://justformylucky.blogspot.com/
  - http://hamtiar.com/
  - http://keluargahamsa.com/
  - https://medium.com/alisoftware
  - https://medium.com/@mxwan
  - https://japanesestation.com/latest-from-japan/
  - https://www.codepolitan.com/articles
  - http://www.hipwee.com/terbaru/
  - http://id.techinasia.com
  - http://cerpenmu.com
  - http://himapsiunmul.blogspot.com
  - http://idntimes.com
  - http://luckty.wordpress.com
  - http://kaskus.co.id
  - http://incefurqan.net
  - http://sinaudev.org
  - http://situsali.com
  - http://rezhajulio.id
  - http://muflihramadhan.com
  - http://robbybie.com
  - http://kangrudi.com
  - http://duniabiza.com
  - http://cutdekayi.com
  - http://www.tukangjalanjajan.com
  - http://zharnd.net
  - http://lendyagasshi.com
  - http://andhikamppp.com
  - http://dianravi.com
  - http://bintangpamungkas.blogspot.com
  - http://nonirosliyani.com
  - http://nsetyo.com
  - https://intanrainy.wordpress.com/