data:
  - http://aasnuraisiyah.blogspot.com
  - http://aisyarifi.wordpress.com
  - http://andhikamppp.com
  - http://aprilecuma.blogspot.com
  - http://aufnote.wordpress.com/
  - http://bintangpamungkas.blogspot.com
  - http://bookie-cookie.blogspot.com
  - http://bulantheirongirl.blogspot.com
  - http://catatanbukudiah.wordpress.com
  - http://cerpenmu.com
  - http://chairulsinaga.blogspot.com
  - http://coretanrifqi.blogspot.com
  - http://cutdekayi.com
  - http://dear-diah.blogspot.com
  - http://dewiultralight08.wordpress.com/
  - http://dhicovelian.wordpress.com
  - http://dianravi.com
  - http://didotanindita.blogspot.com
  - http://donnaimelda.com
  - http://dunia-digital.com/
  - http://duniabiza.com
  - http://dweedy.blogspot.com
  - http://edisipertama.wordpress.com
  - http://erinajulia.wordpress.com
  - http://eternallord.blogspot.co.id/
  - http://evrinasp.wordpress.com
  - http://fandhyachmadromadhon.blogspot.com
  - http://farhanakal.blogspot.com
  - http://felixsiauw.com
  - http://frizkum.blogspot.com
  - http://girlwithwritingproblems.wordpress.com
  - http://goresantintamuslimah.blogspot.com
  - http://halamancermin.blogspot.com
  - http://hamledcreation.blogspot.co.id/
  - http://hamtiar.com/
  - http://hatidanpikiranjernih.blogspot.com
  - http://himapsiunmul.blogspot.com
  - http://hudasyahdan.blogspot.com
  - http://id.kb.kangamir.my.id
  - http://id.techinasia.com
  - http://idntimes.com
  - http://ilarizky.blogspot.com
  - http://incefurqan.net
  - http://intanrainy.wordpress.com/
  - http://isykarima.com
  - http://japanesestation.com/latest-from-japan/
  - http://jurnalotaku.com/all
  - http://justformylucky.blogspot.com/
  - http://kafekopi.blogspot.com
  - http://kangrudi.com
  - http://kaorinusantara.or.id
  - http://kaskus.co.id
  - http://keluargahamsa.com/
  - http://lendyagasshi.com
  - http://liswanti627.blogspot.com
  - http://luckty.wordpress.com
  - http://mansurjihad.com
  - http://medium.com/@mxwan
  - http://medium.com/alisoftware
  - http://menarahati.wordpress.com
  - http://miamiamoy.blogspot.com
  - http://miftaresti.blogspot.com
  - http://mimithpunyacerita.blogspot.com
  - http://mojok.co
  - http://muflihramadhan.com
  - http://mulazamah.com
  - http://mumaken.blogspot.com
  - http://muslimdaily.net
  - http://ndansono.com/
  - http://netriolala.blogspot.com
  - http://nonirosliyani.com
  - http://nsetyo.com
  - http://otacouncil.com/
  - http://rezhajulio.id
  - http://rindhuhati.blogspot.co.id/
  - http://rizkaalyna.blogspot.com
  - http://robbybie.com
  - http://sandibrand.id/
  - http://seindahsunnah.com/
  - http://sinaudev.org
  - http://siochoy.wordpress.com
  - http://situsali.com
  - http://surgabukuku.blogspot.com
  - http://tamvandanberani.blogspot.com
  - http://unyumenyunyu.blogspot.com
  - http://vmatmanegara.blogspot.com
  - http://www.alidabdul.com/
  - http://www.cemaru.com
  - http://www.cewealpukat.me
  - http://www.codepolitan.com/articles
  - http://www.dokterforamen.com
  - http://www.fahmirabbani.com
  - http://www.gendhiss.com
  - http://www.hipwee.com
  - http://www.hipwee.com/terbaru/
  - http://www.idatahmidah.com/
  - http://www.ijeverson.com
  - http://www.ilhamkusumaning.com
  - http://www.jungjawa.com/
  - http://www.jurnalweb.com
  - http://www.kartunet.com
  - http://www.lapakmedan.com
  - http://www.madeinanime.xyz/
  - http://www.maxmanroe.com
  - http://www.nfirmansyah.com
  - http://www.novawijaya.com
  - http://www.nurulfitri.com/
  - http://www.nyorett.com
  - http://www.okymaulana.com/
  - http://www.ridoarbain.com/
  - http://www.syaiha.com
  - http://www.syiahindonesia.com
  - http://www.titisayuningsih.com
  - http://www.tukangjalanjajan.com
  - http://www.unidzalika.com
  - http://www.wignyaharsono.com
  - http://www.wordholic.com
  - http://yukkimura.blogspot.co.id/
  - http://zharnd.net
  - http://www.petanikode.com/
  - http://belajarkoding.net/
  - http://jalantikus.com/
  - http://www.it-jurnal.com/
  - http://www.jagocoding.com/tutorial
  - http://coretanbasayev.blogspot.co.id
  - http://atikahbakir.wordpress.com
  - http://hedirizky.blogspot.co.id
  - http://dongeng-malam.blogspot.co.id
  - http://blograsacerita.wordpress.com
  - http://madamemandana.blogspot.com.au
  - http://mursyidsyaifulhaq27.blogspot.co.id
  - http://storyofrene.blogspot.co.id
  - http://jemarihati23.blogspot.co.id
  - http://muhammadzaini.com
  - http://trisnafadliyah.com
  - http://pebriika.blogspot.co.id
  - http://dewieajaa.blogspot.my
  - http://chairulnisaa.wordpress.com
  - http://alfierani.blogspot.co.id
  - http://auli3ainun.blogspot.co.id
  - http://andiniyulina.blogspot.co.id
  - http://indahnaynes.blogspot.co.id
  - http://banggober.blogspot.co.id
  - http://dlaraz.blogspot.co.id
  - http://ergiwhey.wordpress.com/
  - http://www.andriyani.web.id
  - http://nanaumza.blogspot.co.id
  - http://caklutfi.blogspot.co.id
  - http://pisangbenjol.wordpress.com
  - http://kisahduduk.blogspot.co.id
  - http://caritakita.wordpress.com
  - http://www.nodiwa.com
  - http://bolehdikepoin.blogspot.co.id
  - http://hurairosan.blogspot.co.id